packageExtensions:
  "@tailwindcss/aspect-ratio@*":
    dependencies:
      tailwindcss: "*"
  "@tailwindcss/line-clamp@*":
    dependencies:
      tailwindcss: "*"
  app-builder-lib@*:
    dependencies:
      dmg-builder: "*"
  tailwind-scrollbar@*:
    dependencies:
      tailwindcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-sources.cjs
