nodeLinker: node-modules

packageExtensions:
  "@fullhuman/postcss-purgecss@*":
    dependencies:
      postcss: "*"
  "@tailwindcss/aspect-ratio@*":
    dependencies:
      tailwindcss: "*"
  "@tailwindcss/forms@*":
    dependencies:
      tailwindcss: "*"

plugins:
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: "https://github.com/e5mode/yarn-up-all/releases/download/1.0.3/index.js"

yarnPath: .yarn/releases/yarn-berry.cjs
