yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "postcss-flexbugs-fixes@*":
    dependencies:
      "postcss": "*"
  "@tailwindcss/typography@*":
    dependencies:
      "lodash": "*"
  "react-dnd@*":
    dependencies:
      "@react-dnd/invariant": "*"
  "typeorm@*":
    dependencies:
      "pg": "*"
