yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
packageExtensions:
  "@fullhuman/postcss-purgecss@*":
    dependencies:
      "postcss": "*"
  "@tailwindcss/forms@*":
    dependencies:
      "tailwindcss": "*"
  "@tailwindcss/aspect-ratio@*":
    dependencies:
      "tailwindcss": "*"
