packageExtensions:
  "@tailwindcss/typography@*":
    dependencies:
      lodash: "*"
  postcss-flexbugs-fixes@*:
    dependencies:
      postcss: "*"
  react-dnd@*:
    dependencies:
      "@react-dnd/invariant": "*"
  typeorm@*:
    dependencies:
      pg: "*"

plugins:
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: "https://github.com/e5mode/yarn-up-all/releases/download/1.0.2/index.js"

yarnPath: .yarn/releases/yarn-berry.cjs
