version: '3.8'

services:
  api:
    environment:
      - NODE_ENV=production
    command:
      - /bin/bash
      - -c
      - |
      - yarn run build
      - yarn run start

  frontend:
    environment:
      - NODE_ENV=production
      - NODE_PATH=/usr/src/frontend/src
      - HOST=0.0.0.0
    command:
      - /bin/bash
      - -c
      - |
      - yarn run build
      - yarn run start
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/ssl
    depends_on: 
      - frontend
