version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: always
    expose:
      - "4000"
    environment:
      - NODE_ENV=development
    env_file:
      - api/.env
      - postgres.env
      - aws.env
    volumes:
      - ./api:/usr/src
    depends_on:
      - postgres
      - iframely
      - imageflow

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./frontend:/app
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - NODE_PATH=/usr/src/
      - HOST=0.0.0.0
    depends_on:
      - api

  postgres:
    container_name: postgres
    image: "postgres:alpine"
    restart: always
    env_file:
      - postgres.env
    volumes:
      - "db-data:/var/lib/postgresql/data"
    expose:
      - "5432"

  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
    expose:
      - "6379"

  iframely:
    container_name: iframely
    build: "https://github.com/itteco/iframely.git"
    restart: always
    expose:
      - "8061"
    volumes:
      - ./iframely/iframely.config.js:/iframely/config.local.js
    depends_on:
      - redis

  imageflow:
    container_name: imageflow
    build: ./imageflow
    restart: always
    env_file:
      - aws.env
    ports:
      - "12345:12345"

volumes:
  db-data:
