version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: frontend/Dockerfile
    expose:
      - "4000"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    env_file:
      - api/.env
      - postgres.env
    volumes:
      - .:/src
    depends_on:
      - postgres
      - redis
      - iframely
    command:
      - "yarn run tsc"
      - "yarn run start"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - NODE_ENV=production
      - NODE_PATH=/usr/src/frontend/src
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    env_file:
      frontend/.env
    depends_on:
      - api
    command:
      - "yarn run build"
      - "yarn run start"

  postgres:
    container_name: postgres
    image: "postgres:alpine"
    restart: always
    env_file:
      postgres.env
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  iframely:
    container_name: iframely
    build: "https://github.com/itteco/iframely.git"
    expose:
      - "8061"
    volumes:
      - ./iframely.js:/iframely/config.local.js
    depends_on:
      - redis

  redis:
    container_name: redis
    image: "redis:alpine"
    expose:
      - "6379"

  proxy:
    container_name: proxy
    image: "jwilder/nginx-proxy:alpine"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true

  letsencrypt-companion:
    container_name: letsencrypt
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  db-data:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:

