version: '3.8'

services:
  api:
    environment:
      - NODE_ENV=production
    command:
      - "yarn run tsc"
      - "yarn run start"

  frontend:
    environment:
      - NODE_ENV=production
      - NODE_PATH=/usr/src/frontend/src
      - HOST=0.0.0.0
    command:
      - "yarn run build"
      - "yarn run start"

  proxy:
    container_name: proxy
    image: "jwilder/nginx-proxy:alpine"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true

  letsencrypt-companion:
    container_name: letsencrypt
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
