version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api
    ports:
      - "4000:4000"
    expose:
      - "4000"
    env_file:
      - .env
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/dist
    depends_on:
      - postgres
    command: yarn workspace api run dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/.next
      - "next-cache:/usr/src/app/frontend/.next/cache"
    depends_on:
      - api
    command: yarn workspace frontend run dev

  postgres:
    image: "postgres:alpine"
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - "db-data:/var/lib/postgresql/data"
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  db-data:
  next-cache:
