version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: ../Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      - postgres
      - iframely
      - imageflow

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.nuxt

  redis:
    ports:
      - "6379:6379"

  iframely:
    build: "https://github.com/itteco/iframely.git"
    ports:
      - "8061:8061"
    volumes:
      - ./iframely.config.js:/iframely/config.local.js

  imageflow:
    build: ./imageflow
    ports:
      - "12345:12345"

  postgres:
    container_name: postgres
    image: "postgres:alpine"
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - "db-data:/var/lib/postgresql/data"
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  db-data:
