version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: ../Dockerfile.prod
    environment:
      - NODE_ENV=production
    ports: []

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.prod
    environment:
      - NODE_ENV=production
      - NODE_PATH=/usr/src/frontend/src
      - HOST=0.0.0.0
    ports: []
  
  postgres:
    ports: []
  
  redis:
    ports: []

  iframely:
    ports: []

  imageflow:
    ports: []

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/ssl
    depends_on:
      - frontend
    env_file:
      - nginx/.env

  matomo:
    container_name: matomo
    image: matomo:fpm-alpine
    restart: always
    expose:
      - "9000"
    depends_on:
      - mariadb
    volumes:
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=mariadb
    env_file:
      - matomo.env

  mariadb:
    container_name: mariadb
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - matomo-data:/var/lib/mysql
    env_file:
      - matomo.env

volumes:
  matomo-data:
  matomo:
