version: '3.8'

services:
  api:
    container_name: api
    restart: always
    expose:
      - "4000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      - postgres
      - iframely
      - imageflow

  frontend:
    container_name: frontend
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.nuxt
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    depends_on:
      - api

  postgres:
    container_name: postgres
    image: "postgres:alpine"
    restart: always
    env_file:
      - .env
    volumes:
      - "db-data:/var/lib/postgresql/data"
    expose:
      - "5432"

  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
    expose:
      - "6379"

  iframely:
    container_name: iframely
    restart: always
    expose:
      - "8061"
    volumes:
      - ./iframely.config.js:/iframely/config.local.js
    depends_on:
      - redis

  imageflow:
    container_name: imageflow
    restart: always
    env_file:
      - .env
    expose:
      - "12345"

volumes:
  db-data:
