version: "3.8"

services:
  api:
    image: ghcr.io/comet-app/api:edge
    environment:
      - NODE_ENV=production

  frontend:
    image: ghcr.io/comet-app/frontend:edge
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
  
  iframely:
    image: ghcr.io/comet-app/iframely:edge

  imageflow:
    image: ghcr.io/comet-app/imageflow:edge
  
  nginx:
    container_name: nginx
    image: ghcr.io/comet-app/nginx:edge
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    env_file:
      - .env
