version: "3.9"

services:
  postgres:
    image: "postgres:alpine"
    container_name: postgres
    env_file:
      - .env
    volumes:
      - "db:/var/lib/postgresql/data"
    expose:
      - "5432"
    ports:
      - "5432:5432"

  redis:
    image: "bitnami/redis:latest"
    container_name: redis
    env_file:
      - .env
    expose:
      - "6379"
    ports:
      - "6379:6379"

  server:
    build: Dockerfile
    container_name: server
    ports:
      - "4000:4000"
    expose:
      - "4000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis

volumes:
  db:
