version: "3.8"

services:
  api:
    image: registry.digitalocean.com/cometx/api:latest
    container_name: api
    restart: always
    expose:
      - "4000"
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      - imageflow

  frontend:
    image: registry.digitalocean.com/cometx/frontend:latest
    container_name: frontend
    restart: always
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.nuxt
    depends_on:
      - api

  imageflow:
    image: registry.digitalocean.com/cometx/imageflow:latest
    container_name: imageflow
    restart: always
    expose:
      - "12345"
    env_file:
      - .env

  nginx:
    image: registry.digitalocean.com/cometx/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    env_file:
      - .env
