version: "3.8"

services:
  api:
    build:
      context: api
      dockerfile: dev.Dockerfile
    container_name: api
    ports:
      - "4000:4000"
    expose:
      - "4000"
    env_file:
      - .env
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - postgres

  frontend:
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - api

  postgres:
    image: "postgres:alpine"
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - "db-data:/var/lib/postgresql/data"
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  db-data:
