version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: ../Dockerfile.dev
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.dev
    ports:
      - "3000:3000"

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  iframely:
    build: "https://github.com/itteco/iframely.git"
    ports:
      - "8061:8061"

  imageflow:
    ports:
      - "12345:12345"
