version: "3.8"

services:
  api:
    image: registry.digitalocean.com/cometx/cometx:prod
    container_name: api
    restart: always
    expose:
      - "4000"
    env_file:
      - .env
    command: yarn workspace api run start

  frontend:
    image: registry.digitalocean.com/cometx/cometx:prod
    container_name: frontend
    restart: always
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      - "next-cache:/usr/src/app/frontend/.next/cache"
    command: yarn workspace frontend run start

  nginx:
    image: registry.digitalocean.com/cometx/nginx:prod
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - api
      - frontend

volumes:
  next-cache:
