name: cometx

services:
- name: api
  github:
    repo: cometx-io/cometx
    branch: main
    deploy_on_push: true
  source_dir: api
  dockerfile_path: api/Dockerfile
  http_port: 4000
  routes:
  - path: /api

- name: frontend
  github:
    repo: cometx-io/cometx
    branch: main
    deploy_on_push: true
  source_dir: frontend
  dockerfile_path: frontend/Dockerfile
  http_port: 3000
  routes:
  - path: /

databases:
- name: db
  engine: PG
  production: false
