name: cometx
services:
- name: api
  github:
    repo: cometx-io/cometx
    branch: main
    deploy_on_push: true
  source_dir: api
  environment_slug: node-js
  build_command: yarn build
  run_command: yarn start
  http_port: 4000
  routes:
  - path: /backend
  envs:
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: CA_CERT
    value: ${db.CA_CERT}
  - key: CORS_ORIGIN
    value: ${frontend.PUBLIC_URL}
- name: frontend
  github:
    repo: cometx-io/cometx
    branch: main
    deploy_on_push: true
  source_dir: frontend
  environment_slug: node-js
  build_command: yarn build
  run_command: yarn start
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: API_PRIVATE_URL
    value: ${api.PRIVATE_URL}
  - key: NEXT_PUBLIC_API_PUBLIC_URL
    value: ${api.PUBLIC_URL}
databases:
- name: db
  engine: PG
  production: false
