name: comet
services:
- name: server
  github:
    repo: joincomet/comet
    branch: main
    deploy_on_push: true
  environment_slug: node-js
  run_command: yarn workspace server run start
  http_port: 4000
  routes:
    - path: /api
  envs:
    - key: DATABASE_URL
      value: postgres://${db.USERNAME}:${db.PASSWORD}@${db.HOSTNAME}:${db.PORT}
    - key: DATABASE_NAME
      value: ${db.DATABASE}
    - key: CA_CERT
      value: ${db.CA_CERT}
    - key: CORS_ORIGIN
      value: ${web.PUBLIC_URL}
    - key: ACCESS_TOKEN_SECRET
      value: change this!
    - key: BUCKET
      value: comet
    - key: AWS_ACCESS_KEY_ID
      value: change this!
    - key: AWS_SECRET_ACCESS_KEY
      value: change this!
    - key: AWS_ENDPOINT
      value: nyc3.digitaloceanspaces.com
    - key: MEDIA_DOMAIN
      value: media.joincomet.app
- name: web
  github:
    repo: joincomet/comet
    branch: main
    deploy_on_push: true
  environment_slug: node-js
  build_command: yarn workspace web run build:vite
  output_dir: web/dist
  http_port: 3000
  routes:
    - path: /
  envs:
    - key: SERVER_PATH
      value: ${server.PUBLIC_ROUTE_PATH}
    - key: APP_DOMAIN
      value: ${APP_DOMAIN}
databases:
- name: db
  engine: PG
  production: false
