name: comet
region: nyc
services:
  - name: server
    image:
      registry_type: DOCKER_HUB
      registry: joincomet
      repository: server
      tag: <TAG>
    instance_count: 1
    instance_size_slug: professional-xs
    http_port: 4000
    routes:
      - path: /api
    envs:
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: CA_CERT
        value: ${db.CA_CERT}
      - key: ACCESS_TOKEN_SECRET
        value: <ACCESS_TOKEN_SECRET>
      - key: BUCKET
        value: <BUCKET>
      - key: AWS_ACCESS_KEY_ID
        value: <AWS_ACCESS_KEY_ID>
      - key: AWS_SECRET_ACCESS_KEY
        value: <AWS_SECRET_ACCESS_KEY>
      - key: AWS_ENDPOINT
        value: <AWS_ENDPOINT>
      - key: MEDIA_DOMAIN
        value: <MEDIA_DOMAIN>
  - name: web
    image:
      registry_type: DOCKER_HUB
      registry: joincomet
      repository: web
      tag: <TAG>
    instance_count: 1
    instance_size_slug: professional-xs
    http_port: 3000
    routes:
      - path: /
databases:
  - name: db
    engine: PG
    version: 12
    production: true
    cluster_name: comet
    db_name: comet
    db_user: comet
domains:
  - domain: joincomet.app
    type: PRIMARY
    wildcard: false
