nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: "https://github.com/e5mode/yarn-up-all/releases/download/1.0.3/index.js"

yarnPath: .yarn/releases/yarn-berry.cjs
