name: "Build & Deploy"

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
        with:
          image: frontend
          context: ./frontend
          file: ./Dockerfile.prod

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
        with:
          image: api
          context: ./api
          file: ./Dockerfile.prod

  imageflow:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
        with:
          image: imageflow
          context: ./imageflow
          file: ./imageflow/Dockerfile

  iframely-base:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
        with:
          image: iframely-base
          context: "https://github.com/itteco/iframely.git"
          file: Dockerfile

  iframely:
    needs: [iframely-base]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
        with:
          image: iframely
          context: ./iframely
          file: ./iframely/Dockerfile

  nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
        with:
          image: nginx
          context: ./nginx
          file: ./nginx/Dockerfile
          build-args:
            - CERT="${{ secrets.SSL_CERT }}""
            - KEY="${{ secrets.SSL_KEY }}""

  deploy:
    needs: [frontend, api, imageflow, iframely-base, iframely, nginx]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/deploy
