name: "Build & Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Build container image
        run: docker build ./frontend -t registry.digitalocean.com/cometx/frontend:latest

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/cometx/frontend



  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Build container image
        run: docker build ./api -t registry.digitalocean.com/cometx/api:latest

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/cometx/api
  
  imageflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Build container image
        run: docker build ./imageflow -t registry.digitalocean.com/cometx/imageflow:latest

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/cometx/imageflow

  iframely-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Build container image
        run: docker build https://github.com/itteco/iframely.git -t registry.digitalocean.com/cometx/iframely-base:latest

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/cometx/iframely-base

  iframely:
    needs: [iframely-base]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Build container image
        run: docker build ./iframely -t registry.digitalocean.com/cometx/iframely:latest

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/cometx/iframely

  nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Build container image
        run: docker build ./nginx -t registry.digitalocean.com/cometx/nginx:latest

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/cometx/nginx

  deploy:
    needs: [frontend, api, imageflow, iframely-base, iframely, nginx]
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy
          token: ${{ secrets.WORKFLOW_PAT }}
