name: "Deploy"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Docker-Compose files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          port: 22
          source: "docker-compose.yml,docker-compose.prod.yml"
          target: ${{ github.event.repository.name }}
      - name: Docker-Compose Up
        uses: appleboy/ssh-action@master
        env:
          ENV: ${{ secrets.ENV }}
          REPOSITORY: ${{ github.event.repository.name }}
          USERNAME: ${{ github.repository_owner }}
          CR_PAT: ${{ secrets.CR_PAT }}
        with:
          envs: ENV,REPOSITORY,USERNAME,CR_PAT
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          port: 22
          script: |
            cd $REPOSITORY
            echo -e "$ENV" > .env
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
