name: "Deploy"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          port: 22
          source: "docker-compose.prod.yml"
          target: ${{ github.event.repository.name }}
      - name: Start containers
        uses: appleboy/ssh-action@master
        env:
          ENV: ${{ secrets.ENV }}
          REPOSITORY: ${{ github.event.repository.name }}
        with:
          envs: ENV,REPOSITORY
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          port: 22
          script: |
            cd $REPOSITORY
            echo -e "$ENV" > .env
            mv docker-compose.prod.yml docker-compose.yml
            docker-compose pull -q
            docker-compose up -d
            docker image prune -f
