name: Migrate Production

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Copy migration script
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          port: 22
          source: "./api/src/migrations/migration.sql"
          target: ${{ github.event.repository.name }}
      - name: Run migration
        uses: appleboy/ssh-action@master
        env:
          REPOSITORY: ${{ github.event.repository.name }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        with:
          envs: REPOSITORY, DATABASE_URL, DATABASE_NAME
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          port: 22
          script: |
            cd $REPOSITORY
            doctl databases db delete -f cometx $DATABASE_NAME
            doctl databases db create cometx $DATABASE_NAME
            docker run -d -e POSTGRES_HOST_AUTH_METHOD=trust --name postgres postgres:alpine
            docker cp ./latest.dump postgres:/latest.dump
            docker cp ./migration.sql postgres:/migration.sql
            docker exec postgres pg_restore --verbose --clean --no-acl --no-owner -d ${DATABASE_URL}/${DATABASE_NAME}?sslmode=require ./latest.dump
            docker exec postgres psql -d ${DATABASE_URL}/${DATABASE_NAME}?sslmode=require -f ./migration.sql
            docker stop postgres
            docker rm postgres
            docker run -d --env-file ./prod.env registry.digitalocean.com/cometx/api:prod "yarn run migrate"
