name: "Receive Push"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Build & Deploy"
          token: ${{ secrets.WORKFLOW_PAT }}
          inputs: '{ "environment": "staging" }'
