name: Update Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      message:
        description: Message
        required: true

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging
        uses: actions/checkout@v2
        with:
          ref: staging
      - name: Copy docker-compose files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          port: 22
          source: "docker-compose.prod.yml"
          target: ${{ github.event.repository.name }}
      - name: Rename docker-compose file and prune Docker
        uses: appleboy/ssh-action@master
        env:
          REPOSITORY: ${{ github.event.repository.name }}
        with:
          envs: REPOSITORY
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          port: 22
          script: |
            cd $REPOSITORY
            mv docker-compose.prod.yml docker-compose.yml
            docker system prune -f
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging
        uses: actions/checkout@v2
        with:
          ref: staging
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: Build container image
        run: docker buildx build ./frontend -f ./frontend/Dockerfile.staging -t registry.digitalocean.com/cometx/frontend:staging
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/cometx/frontend
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging
        uses: actions/checkout@v2
        with:
          ref: staging
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: Build container image
        run: docker buildx build ./api -t registry.digitalocean.com/cometx/api:staging
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/cometx/api
  nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging
        uses: actions/checkout@v2
        with:
          ref: staging
      - name: Copy SSL certs
        run: 'echo -e "$SSL_KEY" > ./nginx/key.pem'
        shell: bash
        env:
          SSL_KEY: ${{ secrets.SSL_KEY }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: Build container image
        run: docker buildx build ./nginx -t registry.digitalocean.com/cometx/nginx:latest
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/cometx/nginx
  deploy:
    needs: [prep, frontend, api, nginx]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging
        uses: actions/checkout@v2
        with:
          ref: staging
      - name: Start containers
        uses: appleboy/ssh-action@master
        env:
          REPOSITORY: ${{ github.event.repository.name }}
          ENV: |
            ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}
            BUCKET=${{ secrets.STAGING_BUCKET }}
            MEDIA_DOMAIN=${{ secrets.STAGING_MEDIA_DOMAIN }}
            AWS_ENDPOINT=${{ secrets.AWS_ENDPOINT }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DATABASE_NAME=${{ secrets.STAGING_DATABASE_NAME }}
          NGINX_ENV: STAGING_SUBDOMAIN=${{ secrets.STAGING_SUBDOMAIN }}
        with:
          envs: REPOSITORY, ENV, NGINX_ENV
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          port: 22
          script: |
            cd $REPOSITORY
            touch prod.env
            echo -e "$ENV" > staging.env
            echo -e "$NGINX_ENV" > nginx.env
            docker-compose pull -q
            docker-compose rm -fs nginx
            docker-compose rm -fs frontend-staging
            docker-compose rm -fs api-staging
            docker-compose up -d --no-deps --remove-orphans api-staging
            docker-compose up -d --no-deps frontend-staging
            docker-compose up -d --no-deps nginx
      - name: Send Discord Announcement
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: "Deployment Notifier"
          message: '@everyone Updated Staging (https://${{ secrets.STAGING_SUBDOMAIN }}.cometx.io): ${{ github.event.head_commit.message }}${{ github.event.inputs.message }}'
